cls: Baseline

cfg:
  # spec model
  sr: 48000
  n_fft: 1024
  hop_length: 512
  n_mels: 80

  # model
  n_in_channel: 1
  n_out_channel: 64

  label:
    n_class: 4 # sm, yg, jyp, hybe
    n_dim: 256
  year:
    n_class: 31 # 1994~2024
    n_dim: 256