name: Basic

dataset_name: GTZANDataset

cfg:
  # spec model
  sr: 16000
  clip_len: 15
  n_clip_segment: 1
  n_fft: 1024
  hop_length: 512
  n_mels: 80

  # model
  n_in_channel: 1
  n_out_channel: 64

  n_conv_layer: 3
  kernel_size: 3
  max_pool_size: 3

  n_label_class: 0
  n_year_class: 10 # genres

  label_dim_proportion: 0