column_name:
  artist: artists # TODO(minigb): Change this to singular form 'artist'
  label: label
  label_start: label_start_date
  label_end: label_end_date
  is_train: is_train
  is_test: is_test
  is_benchmark: is_benchmark