column_name:
  song:
    year: year
    title: title
    artist: query_artist
  video:
    year: Year
    title: Song
    artist: Artist
  
  artist: artists # TODO(minigb): Change this to singular form 'artist'
  label: label
  date: release_date
  label_start: label_start_date
  label_end: label_end_date
  is_major_label: is_major_label

# TODO(minigb): This is duplicated. Remove this
csv_column_names:
  song:
    year: year
    title: title
    artist: query_artist
  video:
    year: Year
    title: Song
    artist: Artist