hydra:
  run:
    dir: .

kpop_dataset:
  _dir: kpop-dataset

  song_list_csv_fn: ${_dir}/song_list.csv

  _audio_crawl_result_csv_prefix: ${_dir}/csv/kpop
  chosen_csv_fn: ${_audio_crawl_result_csv_prefix}_chosen.csv
  failed_csv_fn: ${_audio_crawl_result_csv_prefix}_failed.csv
  queries_csv_fn: ${_audio_crawl_result_csv_prefix}_queries.csv

data:
  _dir: . # TODO(minigb): change this to kpop-dataset
  audio_dir: ${_dir}/audio
  recordings_dir: ${_dir}/recordings_per_artist
  artists_dir: ${_dir}/artists_per_label

  _removed_suffix: removed
  removed_audio_dir: ${audio_dir}_${_removed_suffix}
  removed_recordings_dir: ${recordings_dir}_${_removed_suffix}
  removed_artists_dir: ${artists_dir}_${_removed_suffix}

exclude_keywords:
  _dir: excluding_keywords
  video_title_fn: ${_dir}/video_title.json
  song_title_fn: ${_dir}/song_title.json
  song_info_fn: ${_dir}/song_info.json

csv_column_names:
  song:
    year: year
    title: title
    artist: query_artist
  video:
    year: Year
    title: Song
    artist: Artist